CREATE DATABASE IF NOT EXISTS telecom_churn;
USE telecom_churn;

DROP TABLE IF EXISTS customer_churn;
CREATE TABLE customer_churn (
    customer_id VARCHAR(32) PRIMARY KEY,
    gender VARCHAR(16),
    age INT,
    under_30 VARCHAR(8),
    senior_citizen VARCHAR(8),
    married VARCHAR(8),
    dependents VARCHAR(8),
    number_of_dependents INT,
    country VARCHAR(64),
    state VARCHAR(64),
    city VARCHAR(128),
    zip_code INT,
    latitude DECIMAL(10, 6),
    longitude DECIMAL(10, 6),
    population INT,
    quarter VARCHAR(8),
    referred_a_friend VARCHAR(8),
    number_of_referrals INT,
    tenure_in_months INT,
    offer VARCHAR(32) NULL,
    phone_service VARCHAR(8),
    avg_monthly_long_distance_charges DECIMAL(12, 2),
    multiple_lines VARCHAR(8),
    internet_service VARCHAR(8),
    internet_type VARCHAR(32) NULL,
    avg_monthly_gb_download INT,
    online_security VARCHAR(8),
    online_backup VARCHAR(8),
    device_protection_plan VARCHAR(8),
    premium_tech_support VARCHAR(8),
    streaming_tv VARCHAR(8),
    streaming_movies VARCHAR(8),
    streaming_music VARCHAR(8),
    unlimited_data VARCHAR(8),
    contract VARCHAR(32),
    paperless_billing VARCHAR(8),
    payment_method VARCHAR(64),
    monthly_charge DECIMAL(12, 2),
    total_charges DECIMAL(14, 2),
    total_refunds DECIMAL(14, 2),
    total_extra_data_charges DECIMAL(14, 2),
    total_long_distance_charges DECIMAL(14, 2),
    total_revenue DECIMAL(14, 2),
    satisfaction_score INT,
    customer_status VARCHAR(32),
    churn_label VARCHAR(8),
    churn_score INT,
    cltv INT,
    churn_category VARCHAR(64) NULL,
    churn_reason VARCHAR(255) NULL,
    churn_flag TINYINT NOT NULL,
    INDEX idx_contract (contract),
    INDEX idx_status (customer_status),
    INDEX idx_internet_type (internet_type),
    INDEX idx_churn_flag (churn_flag)
);
